get rid of final message step

diff --git a/.github/workflows/check-docs.yml b/.github/workflows/check-docs.yml
--- a/.github/workflows/check-docs.yml
+++ b/.github/workflows/check-docs.yml
@@ -35,28 +35,21 @@ jobs:
         run: yarn
       - name: Run doc generation
         run: yarn docgen:all
-      - name: Check for changes in common/api-review dir (fail if so)
-        id: api-report-check
-        run: |
-          if [[ -n "$(git status common/api-review --porcelain)" ]]; then
-            echo "Unstaged changes detected in api-report(s):"
-            git status -s
-            echo "command-to-run='yarn build'" >> $GITHUB_OUTPUT
-            exit 1
-          fi
-        # Overwrite the command if there are also docs-devsite changes since
-        # running yarn docgen:all will also run yarn build first.
+        # Fail first if there are docs-devsite changes since running yarn docgen:all
+        # will also regenerate any API report changes.
       - name: Check for changes in docs-devsite dir (fail if so)
-        id: docs-check
         run: |
           if [[ -n "$(git status docs-devsite --porcelain)" ]]; then
             echo "Unstaged changes detected in docs-devsite/:"
             git status -s
-            echo "command-to-run='yarn docgen:all'" >> $GITHUB_OUTPUT
+            echo "Changes in this PR affect the reference docs or API reports. Run \`yarn docgen:all\` locally to regenerate the changed files and add them to this PR."
             exit 1
           fi
-      - name: Reference documentation needs to be updated. See message below.
-        if: ${{ failure() }}
-        run: echo "Changes in this PR affect the reference docs or API reports. Run \`$COMMAND_TO_RUN\` locally to regenerate the changed files and add them to this PR."
-        env:
-          COMMAND_TO_RUN: ${{ steps.docs-check.outputs.command-to-run || steps.api-report-check.outputs.command-to-run }}
+      - name: Check for changes in common/api-review dir (fail if so)
+        run: |
+          if [[ -n "$(git status common/api-review --porcelain)" ]]; then
+            echo "Unstaged changes detected in api-report(s):"
+            git status -s
+            echo "Changes in this PR affect the API reports. Run \`yarn build\` locally to regenerate the API reports and add them to this PR."
+            exit 1
+          fi
