new verify job

diff --git a/.github/workflows/test-changed-firestore.yml b/.github/workflows/test-changed-firestore.yml
--- a/.github/workflows/test-changed-firestore.yml
+++ b/.github/workflows/test-changed-firestore.yml
@@ -182,3 +182,15 @@ jobs:
         run: cd packages/firestore && xvfb-run yarn run ${{ matrix.test-name }}
         env:
           BROWSERS: 'Firefox'
+
+  # A job that fails if any required job in the test matrix fails,
+  # to be used as a required check for merging.
+  check-required-tests:
+    runs-on: ubuntu-latest
+    if: always()
+    name: Check all required tests results
+    needs: [test-chrome, compat-test-chrome]
+    steps:
+      - name: Check test matrix
+        if: needs.test-chrome.result == 'failure' || needs.compat-test-chrome.result == 'failure'
+        run: exit 1
